version: '3.8'

services:
  kumawise-proxy:
    build: .
    container_name: kumawise-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - CW_URL=https://api-na.myconnectwise.net/v4_6_release/apis/3.0
      - CW_COMPANY=your_company_id
      - CW_PUBLIC_KEY=your_public_key
      - CW_PRIVATE_KEY=your_private_key
      - CW_CLIENT_ID=your_client_id_optional
      - CW_SERVICE_BOARD=Service Board
      - CW_STATUS_NEW=New
      - CW_STATUS_CLOSED=Closed
      - CW_DEFAULT_COMPANY_ID=ConnectWise_Company_ID_For_Tickets
      # - TRUSTED_IPS=192.168.1.5, 10.0.0.0/24 # Optional: Restrict access to specific IPs/CIDRs. Leave empty or set 0.0.0.0/0 to allow all.

