version: '3.8'

services:
  kumawise-proxy:
    image: ghcr.io/arumes31/kumawise:latest
    container_name: kumawise-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment: &env
      - CW_URL=https://api-na.myconnectwise.net/v4_6_release/apis/3.0
      - CW_COMPANY=your_company_id
      - CW_PUBLIC_KEY=your_public_key
      - CW_PRIVATE_KEY=your_private_key
      - CW_CLIENT_ID=your_client_id
      - CW_SERVICE_BOARD=Service Board
      - CW_STATUS_NEW=New
      - CW_STATUS_CLOSED=Closed
      - CW_DEFAULT_COMPANY_ID=ConnectWise_Company_ID_For_Tickets
      - REDIS_PASSWORD=your_secure_redis_password
      - CELERY_BROKER_URL=redis://:your_secure_redis_password@redis:6379/0
      # - CW_TICKET_PREFIX=Uptime Kuma Alert:
      # - PSA_RATE_LIMIT=60/m
      # - WEBHOOK_SECRET=token1,token2
      # - USE_PROXY=true
      # - PROXY_FIX_COUNT=1
      # - USE_CLOUDFLARE=true
    depends_on:
      - redis

  kumawise-worker:
    image: ghcr.io/arumes31/kumawise:latest
    container_name: kumawise-worker
    restart: unless-stopped
    command: celery -A app.celery worker --loglevel=info
    environment: *env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: kumawise-redis
    restart: unless-stopped
    command: >
      sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=your_secure_redis_password
    volumes:
      - redis_data:/data

volumes:
  redis_data:
